### PR TITLE
Remove trailing whitespaces

### PR DESCRIPTION
**Pull request by ssmolov**
I've found several trailing whitespaces in the code. I suppose they should be removed.

### CODE REVIEW

**Comment by ssmolov** [comment]
It looks like that the problem is not in the pull request itself, but in checks. When I look into "MacOS CI / GNU GCC 9", I see the following error:
```
    /usr/local/opt/gcc@9/bin/g++-9

  is not a full path to an existing compiler tool.
```

**Comment by hriener** [comment]
Yes, not your fault.

Some of the paths in the YAML are outdated.

**Comment by ssmolov** [comment]
Are there any objections against merging this pull request?

**Comment by hriener** [comment]
There is no problem with removing the whitespaces. However, as soon as I accept your PR, lorina's MacOS CI will be marked as `failed` on the entry page.

Consequently, the CI paths need to be fixed first. If you don't want to fix that, then you have to wait until I find time to fix it.

**Comment by hriener** [comment]
Could you merge main such that the CIs triggered.

**Pull request merged**
